# Generated by Django 4.2.5 on 2023-11-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proplandtent', '0007_property_deletedby_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default=None)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_floor', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='None', max_length=250)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.property')),
                ('related_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.units')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
            ],
        ),
    ]
