# Generated by Django 4.2.5 on 2023-11-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyexpenses', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='status',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
