# Generated by Django 4.2.5 on 2023-10-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('property_name', models.CharField(max_length=250)),
                ('property_type', models.CharField(default='residential', max_length=250)),
                ('floors', models.IntegerField(default=0)),
                ('governate', models.CharField(default=None, max_length=300)),
                ('City', models.CharField(default=None, max_length=300)),
                ('Street', models.CharField(default=None, max_length=300)),
                ('Block', models.CharField(default=None, max_length=300)),
                ('property_number', models.IntegerField(default=0)),
                ('parking_areas', models.IntegerField(default=1)),
                ('property_civil_id', models.CharField(default=None, max_length=200)),
                ('underground_floors', models.IntegerField(default=1)),
                ('units_per_floor', models.IntegerField(default=1)),
                ('units_numbers_start_range', models.IntegerField(default=0)),
                ('bathrooms_per_unit', models.IntegerField(default=1)),
                ('area_insqmtrs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('units_details', models.JSONField(default=dict)),
                ('address', models.JSONField(default=dict)),
                ('property_image', models.ImageField(upload_to='images')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('property_status', models.CharField(default='inactive')),
                ('property_description', models.TextField(default=None, max_length=500)),
                ('built_year', models.CharField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistry',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('user_firstname', models.CharField(max_length=150)),
                ('user_lastname', models.CharField(max_length=150)),
                ('user_fullname', models.CharField(default='default', max_length=250)),
                ('user_contact_number', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nationality', models.CharField(max_length=100)),
                ('user_status', models.CharField(default='active', max_length=100)),
                ('user_password', models.CharField(default='abc123', max_length=150)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.role')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_number', models.CharField(default='AB01')),
                ('unit_type', models.CharField(default='other')),
                ('unit_floor', models.CharField(default='AB02')),
                ('unit_bathrooms_nos', models.IntegerField(default=1)),
                ('unit_bedrooms', models.IntegerField(default=0)),
                ('unit_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('area_insqmts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_status', models.CharField(default='unoccupied', max_length=100)),
                ('unit_occupied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
                ('unit_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.property')),
            ],
        ),
        migrations.CreateModel(
            name='TenancyLease',
            fields=[
                ('tenancy_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('yearly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lease_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tenancy_start_date', models.DateField()),
                ('tenancy_end_date', models.DateField()),
                ('tenancy_agreement', models.FileField(upload_to='contract_documents')),
                ('tenancy_status', models.CharField(default='inactive', max_length=150)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.property')),
                ('tenant_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.units')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshTokenRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('role', models.CharField()),
                ('scope', models.CharField()),
                ('status', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(related_name='properties', to='proplandtent.userregistry'),
        ),
    ]
