# Generated by Django 4.2.5 on 2023-09-19 11:03

from django.db import migrations, models
import django.db.models.deletion
import proplandtent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('landlord_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('landlord_email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('properties_owned', models.IntegerField(default=0)),
                ('properties_details', models.JSONField(default=dict)),
                ('landlord_status', models.CharField(default='inactive', max_length=150)),
                ('landlord_password', models.CharField(default='abc123', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('property_name', models.CharField(max_length=250)),
                ('property_type', models.CharField(default='residential', max_length=250)),
                ('floors', models.IntegerField(default=0)),
                ('governate', models.CharField(default=None, max_length=300)),
                ('City', models.CharField(default=None, max_length=300)),
                ('Street', models.CharField(default=None, max_length=300)),
                ('Block', models.CharField(default=None, max_length=300)),
                ('property_number', models.IntegerField(default=0)),
                ('parking_areas', models.IntegerField(default=1)),
                ('propert_civil_id', models.CharField(default='ABFCHF1467', max_length=200)),
                ('underground_floors', models.IntegerField(default=1)),
                ('units_per_floor', models.IntegerField(default=1)),
                ('units_numbers_start_range', models.IntegerField(default=101)),
                ('bathrooms_per_unit', models.IntegerField(default=1)),
                ('area_insqmtrs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('units_details', models.JSONField(default=dict)),
                ('address', models.JSONField(default=dict)),
                ('property_image', models.ImageField(default='/facilitymanager/media/images/r-architecture-TRCJ-87Yoh0-unsplash.jpg', upload_to='facilitymanager/media/images')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('property_status', models.CharField(default='inactive')),
                ('property_description', models.TextField(default=None, max_length=500)),
                ('built_year', models.CharField(default=0)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenant_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('tenants_email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('previous_address', models.TextField(default=None, max_length=500)),
                ('tenant_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('docs', models.FileField(upload_to='facilitymanager/media/documents/tenants_documents')),
                ('tenant_status', models.CharField(default='inactive', max_length=150)),
                ('tenants_password', models.CharField(default='abc123', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistry',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('user_firstname', models.CharField(max_length=150)),
                ('user_lastname', models.CharField(max_length=150)),
                ('user_contact_number', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nationality', models.CharField(max_length=100)),
                ('user_status', models.CharField(default='active', max_length=100)),
                ('user_password', models.CharField(default='abc123', max_length=150)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.role')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_number', models.CharField(default='AB01')),
                ('unit_floor', models.CharField(default='AB02')),
                ('unit_bathrooms_nos', models.IntegerField(default=1)),
                ('area_insqmts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_status', models.CharField(default='unoccupied', max_length=100)),
                ('unit_occupied_by', models.ForeignKey(default=proplandtent.models.get_tenants, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.tenants')),
                ('unit_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.property')),
            ],
        ),
        migrations.AddField(
            model_name='tenants',
            name='app_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry'),
        ),
        migrations.CreateModel(
            name='TenancyLease',
            fields=[
                ('tenancy_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('yearly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lease_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tenancy_start_date', models.DateField()),
                ('tenancy_end_date', models.DateField()),
                ('tenancy_agreement', models.FileField(upload_to='facilitymanager/media/documents/tenancy_documents')),
                ('tenancy_status', models.CharField(default='inactive', max_length=150)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.property')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.units')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(default=proplandtent.models.get_tenants, related_name='properties', to='proplandtent.tenants'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='app_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry'),
        ),
    ]
