# Generated by Django 4.2.5 on 2023-09-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(upload_to='facilitymanager/media/images'),
        ),
    ]
