# Generated by Django 4.2.5 on 2023-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0002_alter_property_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propert_civil_id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='units_numbers_start_range',
            field=models.IntegerField(default=0),
        ),
    ]
