# Generated by Django 4.2.5 on 2023-10-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0003_alter_property_built_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_number',
            field=models.CharField(default=0),
        ),
    ]
