# Generated by Django 4.2.5 on 2023-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0005_units_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancylease',
            name='tenancy_agreement',
            field=models.FileField(upload_to='documents/tenancy_documents'),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='docs',
            field=models.FileField(upload_to='documents/tenants_documents'),
        ),
    ]
