# Generated by Django 4.2.5 on 2023-09-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0006_alter_tenancylease_tenancy_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_occupied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.tenants'),
        ),
    ]
