# Generated by Django 4.2.5 on 2023-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0006_userregistry_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deletedby_user',
            field=models.BooleanField(default=False),
        ),
    ]
