# Generated by Django 4.2.5 on 2023-09-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0007_alter_units_unit_occupied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
