# Generated by Django 4.2.5 on 2023-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0009_rename_propert_civil_id_property_property_civil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
