# Generated by Django 4.2.5 on 2023-09-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0012_alter_property_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
