# Generated by Django 4.2.5 on 2023-10-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0016_alter_tenants_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='reporting_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.landlord'),
        ),
    ]
