# Generated by Django 4.2.5 on 2023-10-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0017_tenants_reporting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancylease',
            name='tenant_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.tenants'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='full_name',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
