# Generated by Django 4.2.5 on 2023-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0018_tenancylease_tenant_id_tenants_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='landlord_fullname',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AddField(
            model_name='userregistry',
            name='user_fullname',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
