# Generated by Django 4.2.5 on 2023-10-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0019_landlord_landlord_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancylease',
            name='tenancy_agreement',
            field=models.FileField(upload_to='contract_documents'),
        ),
        migrations.CreateModel(
            name='RefreshTokenRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('scope', models.CharField()),
                ('status', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
            ],
        ),
        migrations.CreateModel(
            name='AccessTokenRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('scope', models.CharField()),
                ('status', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
            ],
        ),
    ]
