# Generated by Django 4.2.5 on 2023-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0020_alter_tenancylease_tenancy_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokenregistry',
            name='role',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refreshtokenregistry',
            name='role',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
