# Generated by Django 4.2.5 on 2023-10-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0021_accesstokenregistry_role_refreshtokenregistry_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessTokenRegistry',
        ),
    ]
