# Generated by Django 4.2.5 on 2023-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistry',
            name='user_document',
            field=models.FileField(default=None, upload_to='user_documents'),
        ),
        migrations.AddField(
            model_name='userregistry',
            name='user_image',
            field=models.ImageField(default=None, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(upload_to='property_images'),
        ),
    ]
