# Generated by Django 4.2.5 on 2023-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0004_alter_property_property_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_occupied_by',
            field=models.IntegerField(default=0),
        ),
    ]
