# Generated by Django 4.2.5 on 2023-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0009_invoices_tenant_id_alter_invoices_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_type_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(default=None),
        ),
    ]
