# Generated by Django 4.2.5 on 2023-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0013_landlord_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='created_by',
            field=models.BigIntegerField(default=0),
        ),
    ]
