# Generated by Django 4.2.5 on 2023-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0014_landlord_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='subscription_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='subscription_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='time_period_months',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='time_period_year',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
