# Generated by Django 4.2.5 on 2023-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0016_rename_units_numbers_start_range_property_total_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='property_id',
        ),
        migrations.AddField(
            model_name='property',
            name='facilities_available',
            field=models.ManyToManyField(related_name='properties', to='proplandtent.facilities'),
        ),
    ]
