# Generated by Django 4.2.5 on 2023-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0017_remove_facilities_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rentType',
            field=models.CharField(default=None, null=True),
        ),
    ]
