# Generated by Django 4.2.5 on 2023-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0019_facilities_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='country',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='zipcode',
            field=models.BigIntegerField(default=0),
        ),
    ]
