# Generated by Django 4.2.5 on 2023-11-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0020_landlord_country_landlord_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_status',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.status'),
        ),
    ]
