# Generated by Django 4.2.5 on 2023-11-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0022_alter_property_owned_by_alter_units_unit_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit_category',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='unit_kitchens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenancylease',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.property'),
        ),
        migrations.AlterField(
            model_name='tenancylease',
            name='tenant_id',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry'),
        ),
        migrations.AlterField(
            model_name='tenancylease',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.units'),
        ),
    ]
