# Generated by Django 4.2.5 on 2023-11-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0023_units_unit_category_units_unit_kitchens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.status'),
        ),
    ]
