# Generated by Django 4.2.5 on 2023-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0024_alter_units_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='deletedby_user',
            field=models.BooleanField(default=False),
        ),
    ]
