# Generated by Django 4.2.5 on 2023-11-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0025_units_deletedby_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='unit_bedrooms',
            new_name='unit_rooms',
        ),
    ]
