# Generated by Django 4.2.5 on 2023-11-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0026_rename_unit_bedrooms_units_unit_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFamily',
            fields=[
                ('family_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('tenant_relation', models.CharField(max_length=500)),
                ('national_id_no', models.CharField(max_length=500)),
                ('nationality', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenant_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('national_id_no', models.CharField(max_length=1000)),
                ('national_id_expire_date', models.DateField()),
                ('passport_no', models.CharField(max_length=1000)),
                ('passport_expire_no', models.DateField()),
                ('nationality', models.CharField(max_length=500)),
                ('family_status', models.CharField(max_length=300)),
                ('contact_number', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('work_address', models.TextField(max_length=5000)),
                ('facilities', models.ManyToManyField(related_name='tenants', to='proplandtent.facilities')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.status')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.userregistry')),
            ],
        ),
        migrations.CreateModel(
            name='TenantsDocuments',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('document_name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='tenants_images')),
                ('document', models.FileField(upload_to='tenants_documents')),
                ('document_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='TenantFamilyDocuments',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('document_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='tenant_family_documents')),
                ('document', models.FileField(upload_to='tenant_family_documents')),
                ('document_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.tenantfamily')),
            ],
        ),
        migrations.AddField(
            model_name='tenantfamily',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.tenants'),
        ),
    ]
