# Generated by Django 4.2.5 on 2023-11-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0027_tenantfamily_tenants_tenantsdocuments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants',
            old_name='passport_expire_no',
            new_name='passport_expire_date',
        ),
    ]
