# Generated by Django 4.2.5 on 2023-11-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0028_rename_passport_expire_no_tenants_passport_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants',
            old_name='family_status',
            new_name='marital_status',
        ),
    ]
