# Generated by Django 4.2.5 on 2023-11-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0029_rename_family_status_tenants_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRequiredDocuments',
            fields=[
                ('requirement_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
