# Generated by Django 4.2.5 on 2023-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0030_tenantrequireddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfamilydocuments',
            name='expire_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
