# Generated by Django 4.2.5 on 2023-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0031_tenantfamilydocuments_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='national_id_expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='national_id_no',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='passport_expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='passport_no',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
