# Generated by Django 4.2.5 on 2023-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0032_alter_tenants_national_id_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='created_by',
            field=models.BigIntegerField(default=0),
        ),
    ]
