# Generated by Django 4.2.5 on 2023-11-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplandtent', '0033_tenants_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='rent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenancy_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenancy_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proplandtent.units'),
        ),
    ]
